server:
  port: 8082

pages:
  extract:
    path:

spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: challenge

challenge:
  task:
    ttl-ms: 60000
  plugins:
    priority-override: ""

resilience4j:
  circuitbreaker:
    instances:
      pluginTransport:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50.0
        slowCallRateThreshold: 100.0
        slowCallDurationThreshold: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30000
        recordExceptions:
          - ge.becrin.pouwer.pow.service.PluginTransportException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
