services:
  monero-testnet:
    image: sethsimmons/simple-monerod:v0.18.3.4
    container_name: monero-testnet
    restart: unless-stopped
    networks:
      - monero-net
    ports:
      - "18089:18089"     # JSON‑RPC restricted
      - "18088:18088"     # ZMQ
    volumes:
      - monero-testnet-data:/home/monero/.bitmonero
    command:
      - --testnet
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --zmq-pub=tcp://0.0.0.0:18088
      - --no-igd
      - --enable-dns-blocklist
      - --prune-blockchain
      - --confirm-external-bind

  p2pool:
    image: sethsimmons/p2pool:v4.3
    container_name: p2pool
    restart: unless-stopped
    networks:
      - monero-net
    ports:
      - "3333:3333"
      - "37889:37889"
    volumes:
      - p2pool-data:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    # This abomination came from space separated parameters and arguments
    command:
      - --host
      - "monero-testnet"
      - --rpc-port
      - "18089"
      - --zmq-port
      - "18088"
      - --wallet
      - "468ydghFfthE3UTc53eF5MP9UyrMcUiAHP5kizVYJsej5XGaXBoAAEzUHCcUF7t3E3RrYAX8Rs1ujhBdcvMpZSbH8qkb55R"
      - --stratum
      - "0.0.0.0:3333"
      - --p2p
      - "0.0.0.0:37889"

networks:
  monero-net:
    name: monero-testnet_default

# TODO Make externalizable
volumes:
  monero-testnet-data:
  p2pool-data:
  wallet-data:
