services:
  monero-testnet:
    image: ghcr.io/sethforprivacy/simple-monerod:v0.18.4.6
    container_name: monero-testnet
    restart: unless-stopped
    networks:
      - monero-net
    ports:
      - "18089:18089" # JSON-RPC restricted
      - "18088:18088" # ZMQ
    volumes:
      - type: bind
        source: D:/docker/monero-testnet-data
        target: /home/monero/.bitmonero
    command:
      - --testnet
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --zmq-pub=tcp://0.0.0.0:18088
      - --no-igd
      - --enable-dns-blocklist
      - --prune-blockchain
      - --sync-pruned-blocks
      - --confirm-external-bind

  p2pool:
    image: ghcr.io/sethforprivacy/p2pool:v4.15
    container_name: p2pool
    restart: unless-stopped
    depends_on:
      monero-testnet:
        condition: service_started
    networks:
      - monero-net
    ports:
      - "3333:3333"
      - "37888:37888"
    volumes:
      - p2pool-data:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    command:
      - --host
      - "monero-testnet"
      - --rpc-port
      - "18089"
      - --zmq-port
      - "18088"
      - --wallet
      - "9wDZ4yA7aqiNQfnFrKsKQPM4jHyYRcdHdP5d5FDGa12YDs7QBFPwXgyZuk9WnCfAdvAKRWk4psFsYXb55xYGHgxmF6cxpUj"
      - --stratum
      - "0.0.0.0:3333"
      - --p2p
      - "0.0.0.0:37888"
      - --loglevel
      - "4"
      - --mini

  pouwer-server:
    image: localhost:9002/pouwer-server:0.1.0
    container_name: pouwer-server
    restart: unless-stopped
    environment:
      CHALLENGE_PLUGINS_DIRECTORY: /plugins
      STRATUM_HOST: p2pool
    ports:
      - "8082:8082"
    depends_on:
      p2pool:
        condition: service_started
      plugin-sync:
        condition: service_completed_successfully
    volumes:
      - pouwer-plugin-data:/plugins
    networks:
      - monero-net
      - app-net

  plugin-sync:
    build:
      context: ./plugin-sync-container
    container_name: plugin-sync
    restart: "no"
    environment:
      PLUGIN_REPO_URL: http://host.docker.internal:9001/repository/maven-hosted
      PLUGIN_TARGET_DIR: /plugins
    command:
      - --no-clean
      - --artifact
      - ge.becrin.pouwer:payload-bitcoin-rpc:0.1.0
      - --artifact
      - ge.becrin.pouwer:payload-sha256:0.1.0
      - --artifact
      - ge.becrin.pouwer:payload-monero-randomx:0.1.0
    volumes:
      - pouwer-plugin-data:/plugins
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  monero-net:
    name: monero-testnet_default
  app-net:

volumes:
  monero-testnet-data:
  p2pool-data:
  wallet-data:
  server-postgres-data:
  pouwer-plugin-data:

