apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: pouwer-system
spec:
  plugin:
    bouncer:
      enabled: true
      logLevel: INFO
      updateIntervalSeconds: 30
      defaultDecisionSeconds: 1
      httpTimeoutSeconds: 10
      crowdsecMode: live
      crowdsecLapiPath: /
      crowdsecLapiKey: replace-with-long-random-key
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiScheme: http
      # Pouwer Integration
      captchaProvider: custom
      captchaCustomKey: pouwer-firewall
      captchaCustomJsURL: "https://192.168.17.177/static/monero/challenge-monero.js?pluginId=monero-randomx"
      captchaCustomValidateURL: "http://pouwer-server.pouwer-system.svc.cluster.local:8082/validate-custom-captcha"
      captchaCustomResponse: response
      captchaHTMLFilePath: "/pages/challenge.html"
      banHTMLFilePath: "/pages/ban.html"
      captchaGracePeriodSeconds: 60
      remediationHeadersCustomName: X-Crowdsec-Remediation
