@startuml
skinparam actorStyle awesome
skinparam componentStyle rectangle
skinparam shadowing false

top to bottom direction

package "Browser Client" as Browser #lightblue {
  actor User
  collections "PoUW Scripts\nRandomX.js/BTC Regtest\n(JS/WASM)" as Miner
  component "Worker Engine" as Worker
}

package "API Client" as APIClient #lightblue {
  actor "API User" as APIUser
  collections "Miner\n(XMRig)" as StandaloneMiner
  component "Standalone Worker Engine" as StandaloneWorker
}

package "Resource" {
    component "API Resource" as APIResource
    component "Web Resource" as WebResource
}

package "Edge" #lightyellow {
    component "Rate Limiter/Load Balancer\n(Traefik)" as RateLimiter
    component "Security Engine\n(CrowdSec)" as SecurityEngine
    component "Remediation Middleware\n(crowdsec-bouncer-traefik-plugin)" as Middleware
}

package "Reputation Engine" #pink {
    component "Reputation Service" as ReputationService
    component "Difficulty Controller" as DifficultyController
}

package "Framework Core" #pink {
  component "Worker Server" as WorkerServer
  component "Task Orchestrator" as Orchestrator
  component "Result Service" as ResultService
}

package "Abstraction Layer" #lightgreen {
  component "Custom Monero Stratum Adapter" as MoneroAdapter
  component "Custom BTC Regtest Client" as BTCRegtestClient
  collections "Other Payload Adapters" as OtherPayload
}

package "External Providers" #lightgreen {
  component "P2Pool Monero\n(RandomX Mining Pool)" as P2Pool
  component "Monero Node" as XMRNode
  component "BTC Regtest Node" as BTCRegtest
  collections "Other External Providers" as OtherProviders
}

DifficultyController <-down-> Orchestrator
DifficultyController <-right-> ReputationService
ReputationService -right-> Middleware
ResultService -up-> ReputationService

User -down-> RateLimiter: Request
RateLimiter -down-> WebResource: Request
RateLimiter -down-> APIResource: Request

Miner <-down-> Worker

WorkerServer <-up-> Worker
Worker <-down-> Orchestrator

ResultService -up-> Middleware

Middleware <-up-> SecurityEngine
RateLimiter <-> Middleware

Middleware <-> Worker

ResultService <-down-> MoneroAdapter
Orchestrator <-down-> MoneroAdapter

ResultService <-down-> BTCRegtestClient
Orchestrator <-down-> BTCRegtestClient

ResultService <-down-> OtherPayload
Orchestrator <-down-> OtherPayload

MoneroAdapter <-down-> P2Pool: Stratum
BTCRegtestClient <-down-> BTCRegtest: JSON-RPC
OtherPayload <-down-> OtherProviders

P2Pool -right-> XMRNode: JSON-RPC
@enduml
