@startuml
skinparam actorStyle awesome
skinparam componentStyle rectangle
skinparam shadowing false

top to bottom direction

package "Browser Client" as Browser {
  actor User
  collections "PoUW Scripts\nRandomX.js/BTC Regtest\n(JS/WASM)" as Miner #lightgreen
  component "Worker Engine" as Worker #lightgreen
}

package "API Client" as APIClient {
  actor "API User" as APIUser
  collections "Miner\n(XMRig)" as StandaloneMiner #pink
  component "Standalone Worker Engine" as StandaloneWorker #pink
}

package "Resource" {
    component "API Resource" as APIResource
    component "Web Resource" as WebResource
}

package "Edge" {
    component "Rate Limiter/Load Balancer\n(Traefik)" as RateLimiter #lightgreen
    component "Security Engine\n(CrowdSec)" as SecurityEngine #lightgreen
    component "Remediation Middleware\n(crowdsec-bouncer-traefik-plugin)" as Middleware #lightgreen
}

package "Reputation Engine" {
    component "Reputation Service" as ReputationService #pink
    component "Difficulty Controller" as DifficultyController #pink
}

package "Framework Core" {
  component "Worker Server" as WorkerServer #lightgreen
  component "Task Orchestrator" as Orchestrator #lightgreen
  component "Result Service" as ResultService #lightgreen
}

package "Abstraction Layer" {
  component "Custom Monero Stratum Adapter" as MoneroAdapter #lightgreen
  component "Custom BTC Regtest Client" as BTCRegtestClient #lightgreen
  collections "Other Payload Adapters" as OtherPayload #pink
}

package "External Providers" {
  component "P2Pool Monero\n(RandomX Mining Pool)" as P2Pool
  component "Monero Node" as XMRNode
  component "BTC Regtest Node" as BTCRegtest
  collections "Other External Providers" as OtherProviders
}

DifficultyController <-down-> Orchestrator
DifficultyController <-right-> ReputationService
ReputationService -right-> Middleware
ResultService -up-> ReputationService

User -down-> RateLimiter: Request
RateLimiter -down-> WebResource: Request
RateLimiter -down-> APIResource: Request

Miner <-down-> Worker

WorkerServer <-up-> Worker
Worker <-down-> Orchestrator

ResultService -up-> Middleware

Middleware <-up-> SecurityEngine
RateLimiter <-> Middleware

Middleware <-> Worker
ResultService <-down-> MoneroAdapter
Orchestrator <-down-> MoneroAdapter

ResultService <-down-> BTCRegtestClient
Orchestrator <-down-> BTCRegtestClient

ResultService <-down-> OtherPayload
Orchestrator <-down-> OtherPayload

MoneroAdapter <-down-> P2Pool: Stratum
BTCRegtestClient <-down-> BTCRegtest: JSON-RPC
OtherPayload <-down-> OtherProviders

P2Pool -right-> XMRNode: JSON-RPC
@enduml
