services:
  backend:
    image: ${BACKEND_IMAGE:-pouw-backend:local}
    container_name: pouw-backend
    ports:
      - "8082:8082"
    restart: unless-stopped
    environment:
      STRATUM_HOST: p2pool

volumes:
  backend-postgres-data:
