server {
  listen 3001;
  server_name _;
  root /usr/share/nginx/html;
  index challenge.html;

  location /assets/ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /challenge.html;
  }
}
