apiVersion: v1
kind: ConfigMap
metadata:
  name: api-auth-nginx-conf
data:
  default.conf: |
    server {
      listen 80;

      location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
      }

      location = /check {
        if ($http_authorization = "") {
          return 401;
        }
        return 200;
      }

      location / {
        return 404;
      }
    }

