apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-nginx-conf
data:
  default.conf: |
    server {
      listen 80;

      location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }
