@startuml
skinparam actorStyle awesome
skinparam componentStyle rectangle
skinparam shadowing false

top to bottom direction

package "Client" {
  actor User
  component "Execution Engine\n(JS/WASM Worker)" as Worker
}

package "Framework Core" {
  component "Gateway" as Gateway
  component "Task Orchestrator" as Orchestrator
  component "Result Service" as ResultService
}

package "Abstraction Layer" {
  component "Task Generator Interface" as TaskIF
  component "Validation Interface" as ValidationIF
}

package "Payload Modules" {
  component "Task Generator\nImplementation" as TaskGen
  component "Validation Module\nImplementation" as ValidationModule
}

User --> Gateway

Gateway -> Orchestrator
ResultService -> Gateway

Orchestrator -up-> Worker

Worker -down-> ResultService

ResultService <-down-> ValidationIF
Orchestrator <-down-> TaskIF

TaskIF <-down-> TaskGen
ValidationIF <-down-> ValidationModule
@enduml
