kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pouwer-dev

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

  - role: worker
    extraMounts:
      - hostPath: D:/docker/monero-mainnet-data
        containerPath: /mnt/monero-data
      - hostPath: D:/docker/pouwer-pages
        containerPath: /mnt/pouwer-pages

  - role: worker
    extraMounts:
      - hostPath: D:/docker/monero-mainnet-data
        containerPath: /mnt/monero-data
      - hostPath: D:/docker/pouwer-pages
        containerPath: /mnt/pouwer-pages

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."172.21.0.1:9002"]
      endpoint = ["http://172.21.0.1:9002"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."172.21.0.1:9002".tls]
      insecure_skip_verify = true

networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
