services:
  monero-mainnet:
    image: sethsimmons/simple-monerod:v0.18.3.4
    container_name: monero-mainnet
    restart: unless-stopped
    networks:
      - monero-net
    ports:
      - "28089:18089"     # JSON‑RPC restricted
      - "28088:18088"     # ZMQ
    volumes:
      - type: bind
        source: D:/docker/monero-mainnet-data
        target: /home/monero/.bitmonero
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --zmq-pub=tcp://0.0.0.0:18088
      - --no-igd
      - --enable-dns-blocklist
      - --prune-blockchain
      - --sync-pruned-blocks
      - --confirm-external-bind

  p2pool:
    image: sethsimmons/p2pool:v4.3
    container_name: p2pool
    restart: unless-stopped
    networks:
      - monero-net
    ports:
      - "3333:3333"
      - "37889:37889"
    volumes:
      - p2pool-data:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    # This abomination came from space separated parameters and arguments
    command:
      - --host
      - "monero-mainnet"
      - --rpc-port
      - "18089"
      - --zmq-port
      - "18088"
      - --wallet
      - "9wDZ4yA7aqiNQfnFrKsKQPM4jHyYRcdHdP5d5FDGa12YDs7QBFPwXgyZuk9WnCfAdvAKRWk4psFsYXb55xYGHgxmF6cxpUj"
      - --stratum
      - "0.0.0.0:3333"
      - --p2p
      - "0.0.0.0:37889"

networks:
  monero-net:
    name: monero-mainnet_default

# TODO Make externalizable
volumes:
  monero-mainnet-data:
  p2pool-data:
  wallet-data:
